### ISSUE TITLE
"WRITE" placeholder in README

### ISSUE THREAD

**Issue by bdelepine** [brsynth/RetroPathRL#1]
Hello @tduigou,

Il y a des "WRITE" dans le README qui sont, j'imagine, des placeholders pour des liens ou autre.

Par ailleurs, quel est le status de développement de RP3 ? Est-ce que tu serais intéressé par une liste de ce que je trouve contre-intuitif à l’installation et à l'usage ? Réponds-moi par MP si tu préfères.

Merci !

**Comment by tduigou** [comment]
Hello @bdelepine,

Les placeholders étaient effectivement là pour pointer vers le scope viewer. Merci pour le retour. 

Je réponds ici dans les grandes lignes à propos du statut du développement.

Dans l'immédiat, le développement "actif" de RetroPath RL est en pause, car mon temps est pris par d'autres projets, et Mathilde Koch (@MathildeKoch) qui a développé une grande partie de l'outil a terminé sa thèse chez nous.

Cela dit, toutes suggestions pour faciliter l'utilisation de l'outil sont les bienvenues et seront intégrées dans la mesure du possible.

Il y a aussi des améliorations du coeur de l'outil qui sont d'intérêts. Je pense par exemple à une gestion optimisée de la mémoire et le support du multi-thread, qui permettraient une exploration plus rapide. Ces chantiers demandant un investissement plus important, ils sont pour le moment relégués au long terme.

Tes retours sur l'installation et l'usage sont donc les bienvenus, et je te propose d'en discuter plus en détails en MP.

À bientôt !
