### ISSUE TITLE
FileNotFoundError:full_rules_forward_H.pkl

### ISSUE THREAD

**Issue by HanMengying** [brsynth/RetroPathRL#10]
When I run the Testing and Command line examples I find that a file called full_rules_forward_H.pkl is always missing.
FileNotFoundError: [Errno 2] No such file or directory: '/home/madeline/MCTS/RetroPathRL/data/rules/full_rules_forward_H.pkl'
![image](https://user-images.githubusercontent.com/50348328/149276962-4947f9de-c5bd-4012-af99-6d2cffb5063c.png)

**Comment by tduigou** [comment]
Hello, what is the command line used?

**Comment by HanMengying** [comment]
python change_config.py --use_cache True --add_Hs True 
pytest -v
Neither of these two steps will succeed.
![image](https://user-images.githubusercontent.com/50348328/149448122-ba76c6e3-55ea-48d2-9baa-7a39091f7437.png)

**Comment by tduigou** [comment]
Prior to that, did you follow the `Set-up data files` section? https://github.com/brsynth/RetroPathRL#set-up-data-files .

**Comment by HanMengying** [comment]
In the data setup step,I chose the default path. In my opinion, the file should be in the data you provided, but I didn't find it
.Or does this file named full_rules_forward_H.pkl need to be provided by the user?
![image](https://user-images.githubusercontent.com/50348328/149515671-3a177adc-2792-42ea-9337-0845ee43bffc.png)

**Comment by tduigou** [comment]
No, the reaction rules should be downloaded from the RetroRules website, and then preparsed following the "Set-up data files" section. Here the link to download the rules (donwload the 2 datasets compatible with RetroPathRL, one with and the other without explicit Hs): https://retrorules.org/dl.

**Comment by HanMengying** [comment]
Thanks a lot. I really appreciate your help. It works!

**Comment by JustinDoIt** [comment]
Hello, https://retrorules.org/dl is not reachable. Any other way to download it?

**Comment by HanMengying** [comment]
The website is down, maybe you can wait.

**Comment by tduigou** [comment]
Hello @JustinDoIt, RetroRules is up again. Thanks for your help.

**Comment by JustinDoIt** [comment]
Thanks for your active maintenance! RetroPathRL is a superpower tool and you're really a super nice team.
