### ISSUE TITLE
Errors in Set-up data files

### ISSUE THREAD

**Issue by JuanLuGMid** [brsynth/RetroPathRL#11]
Hello, 

First of all, thanks for this amazing tool. I'm getting errors when I run `python calculate_organisms.py` . Previously, I've downloaded the retrorules from https://retrorules.org/dl and did not get any problem. The errors looks like this:

<img width="947" alt="RetroPathRL__error_1" src="https://user-images.githubusercontent.com/94532582/170668288-f4a27a0c-ffe2-4281-8422-aca03f72a94b.PNG">

Then, when I run `pytest -v` I get 44 failed, 67 passed tests. I suppose it is motivated by the errors in the image above. Something strage is that I do not have the folder 'organisms' in 'data'.

Thanks in advance.

**Comment by tduigou** [comment]
Hi @JuanLuGMid, did you double check you follow the instructions to create and activate the conda environement? What does `conda list` returns?

**Comment by JuanLuGMid** [comment]
Thanks for your answer. I reintalled RetroPathRL an I'm getting the same problem. I think I carefully followed the commands to create the environment (MCTS) and install the needed packages. If I run `conda list` I get:

\# Name                    Version                   Build  Channel
atomicwrites              1.4.0                      py_0
attrs                     21.4.0             pyhd3eb1b0_0
blas                      1.0                         mkl
cairo                     1.14.12              hf171d8a_3
certifi                   2021.5.30        py36haa95532_0
colorama                  0.4.4              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
importlib-metadata        4.8.1            py36haa95532_0
importlib_metadata        4.8.1                hd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2022.0.0          haa95532_3663
jpeg                      9e                   h2bbff1b_0
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.2.0                he0120a3_1
lz4-c                     1.9.3                h2bbff1b_1
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py36hdbbee80_0
mkl_random                1.0.1            py36h77b88f5_1
more-itertools            8.12.0             pyhd3eb1b0_0
numpy                     1.15.4           py36ha559c80_0
numpy-base                1.15.4           py36h8128ebf_0
olefile                   0.46                     py36_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.1.5            py36hd77b12b_0
pillow                    8.3.1            py36h4fa10fc_0
pip                       21.2.2           py36haa95532_0
pixman                    0.40.0               h2bbff1b_1
pluggy                    0.13.1           py36haa95532_0
py                        1.11.0             pyhd3eb1b0_0
py-boost                  1.67.0           py36h8300f20_4
pymongo                   3.12.0           py36hd77b12b_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pytest                    6.2.4            py36haa95532_2
python                    3.6.13               h3758d61_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytz                      2021.3             pyhd3eb1b0_0
pyyaml                    5.4.1            py36h2bbff1b_1
rdkit                     2019.03.1.0      py36h3d1ada6_1    rdkit
rp3                       0.0                       dev_0    <develop>
rp3-dcache                0.3                       dev_0    <develop>
scikit-learn              0.19.1           py36hae9bb9f_0
scipy                     1.1.0            py36h4f6bf74_1
setuptools                58.0.4           py36haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.3               h2bbff1b_0
tbb                       2021.5.0             h59b6b97_0
tbb4py                    2021.3.0         py36h59b6b97_0
tk                        8.6.11               h2bbff1b_1
toml                      0.10.2             pyhd3eb1b0_0
typing_extensions         4.1.1              pyh06a4308_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.5                h8cc25b3_1
yaml                      0.2.5                he774522_0
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.12               h8cc25b3_2
zstd                      1.5.2                h19a0ad4_0

**Comment by tduigou** [comment]
Re-reading the thread, here what I think.

It is "normal" that some errors appear in the logs during the `calculate_organisms.py` execution. This is because some compounds defined in chassis appear to be not valid compounds. However, a folder should have been created at the end of the execution with some pickle files inside it.

RetroPathRL has been developped and tested using Linux and Mac operating systems. Some functionnalities embedded into the code -- the first one that come to my mind is the methods to time out / kill rule applications taking too much time -- will not work with a Windows OS. Hence, RetroPathRL is not fully usable with Windows.

I'll mention the OS compatibilities in the README so that this is clearly stated.

If you can use a Linux or Mac that should fix the issues you met. Sorry again for the delay.
