### ISSUE TITLE
Is it possible to use your tools in reverse?

### ISSUE THREAD

**Issue by LeungYpH** [brsynth/RetroPathRL#12]
Hello! 
thanks for developing such an amazing tool!
I feel that your software is usually used to screen for pathways to synthesize certain products. 
Now, I tried to search through your software to find out the pathways by which E. coli **consumes** estrogens.
I did the following works:
1. add the estrogen information to sink file(iJO1366.csv)
2. both using the rule file of RetroPath tutorial_data and retrorules_rr02_rp2_flat_all.csv
3. modified source.csv by adding succinate into it(assuming the estrogen will finally enter TCA)

I feel that there is a big problem with this method, because sink is likely to generate succinate through other substances inside.
So it is possible to do this work through RetroPath? I beg you provide some suggestion about this. Thank you!

**Comment by tduigou** [comment]
Hello @LeungYpH,

Indeed RetroPathRL has been designed for predicting biosynthetic pathways for bioproduction. However, you could the following settings that could bring you toward your goal:

- a `source.csv` file containing the estrogens structure only
- a `sink.csv` file containing the list of ecoli compounds (and add to it succinate if needed)
- a rule file containing the rules annotated for a forward usage

This way, the algorithm starts from the source file (estrogen), and will apply reaction rules on it, which will generate intermediate compounds until it reaches compounds already present in the sink, i.e. natively present in E. coli. 

Best regards,
