### ISSUE TITLE
ERROR rp3_dcache/test/test_Manager.py

### ISSUE THREAD

**Issue by ericjuo** [brsynth/RetroPathRL#16]
Hi,
I tried to install the package today and run the pytest -v. The test failed to import module named  'rp3_dcache.Manager' and 'rp3_dcache.Utils', but i have clone the https://github.com/brsynth/rp3_dcache.git.
How can I solve this error?
============================= test session starts ==============================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /home/ncku2/anaconda3/envs/RetropathRL/bin/python
cachedir: .pytest_cache
rootdir: /home/ncku2/jjj/RetropathRL/RetroPathRL
collected 111 items / 2 errors / 109 selected                                  

==================================== ERRORS ====================================
_______________ ERROR collecting rp3_dcache/test/test_Manager.py _______________
ImportError while importing test module '/mypath/RetroPathRL/rp3_dcache/test/test_Manager.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda3/envs/RetropathRL/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
rp3_dcache/test/test_Manager.py:2: in <module>
    from rp3_dcache.Manager import Manager
E   ModuleNotFoundError: No module named 'rp3_dcache.Manager'
________________ ERROR collecting rp3_dcache/test/test_Utils.py ________________
ImportError while importing test module '/mypath/RetroPathRL/rp3_dcache/test/test_Utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda3/envs/RetropathRL/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
rp3_dcache/test/test_Utils.py:4: in <module>
    from rp3_dcache.Utils import default_config, make_document_id, as_document, rdmols_from_document
E   ModuleNotFoundError: No module named 'rp3_dcache.Utils'
=========================== short test summary info ============================
ERROR rp3_dcache/test/test_Manager.py
ERROR rp3_dcache/test/test_Utils.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 2.82s ===============================

**Comment by tduigou** [comment]
Hi @ericjuo, did you follow the rp3_cache installation instructions?

**Comment by ericjuo** [comment]
> Hi @ericjuo, did you follow the rp3_cache installation instructions?

I do follow the installaion steps of rp3_cache. The following is the code I run under rp3_decache directory:
```
conda create --name myenv python=3.6
source activate myenv
conda install --channel rdkit rdkit=2018.09.1.0
conda install --channel conda-forge pytest
conda install pytest
conda install pymongo
conda install pyyaml
pip install -e .
```
I think this might stem from importing scripts from the incorrect folder?
I cloned the rp3_dcache folder in the RetroPathRL directory. Is this the right path to place rp3_dcache folder?

**Comment by tduigou** [comment]
Hi @ericjuo, sorry for my delayed answer. The issue might come from directory location chosen for rp3_cache. I suggest trying to install rp3_cache outside of the retrorules installation folder. Then remove and re-recreate the `myenv` conda env.

Best wishes,
Thomas

**Comment by ericjuo** [comment]
Hi @tduigou ,
It worked! I have successfully installed the rp3_cache.

Thank you!

**Comment by tduigou** [comment]
Great to here! I close the issue.
