### ISSUE TITLE
I can't use other organism except ecoli and ijo1366

### ISSUE THREAD

**Issue by Teintes-BI** [brsynth/RetroPathRL#17]
Hello! 
First of all, thank you very much for your program! 
However, I've recently encountered some issues while using it. I followed the installation instructions in the Readme document exactly. 
During the process, after running `python calculate_organisms.py`, I noticed an error in the [logs_organisms_set_up.log](https://github.com/brsynth/RetroPathRL/files/14773404/logs_organisms_set_up.log) file in the data/organisms folder. 
Additionally, when using `Python Tree.py` for pathway prediction, I found that I am unable to specify organisms other than ecoli or ijo1366.
```
python Tree.py \
    --log_file tree.log \
    --itermax 10000 \
    --expansion_width 10 \
    --time_budget 10800 \
    --organism_name bsubtilis \
    --max_depth 7 \
    --UCT_policy Biochemical_UCT_1 \
    --UCTK 2 \
    --Rollout_policy Rollout_policy_random_uniform \
    --max_rollout 10 \
    --chemical_scoring SubandprodChemicalScorer \
    --virtual_visits 0 \
    --diameter 2 4 8 16 \
    --c_name IPDO \
    --c_inchi "InChI=1/C5H12O2/c1-5(2,7)3-4-6/h6-7H,3-4H2,1-2H3" \
    --folder_to_save exec/IPDO \
    --biological_score_cut_off 0.3  \
    --substrate_only_score_cut_off 0.1 \
    --chemical_score_cut_off 0.3 \
    --minimal_visit_counts 1 \
    --fire_timeout 1 \
    --penalty -1 \
    --full_state_reward 10 
```
and i get 

```Traceback (most recent call last):
  File "Tree.py", line 1584, in <module>
    __cli()
  File "Tree.py", line 1407, in __cli
    organism = get_organism(biosensor, organism_name = args.organism_name, complementary_sink = args.complementary_sink, add_Hs = add_Hs)
  File "Tree.py", line 1179, in get_organism
    organism = bsubtilis_H
NameError: name 'bsubtilis_H' is not defined
```
looking forward to your reply !

**Comment by tduigou** [comment]
Hello @Teintes-BI, sorry for this delayed reply, I was busy the whole last week giving Python lessons.

Indeed, there was an issue while trying use some sinks (thanks pointing that). I pushed a fix that now should resolve the issue, which means the `bsubtilis` should now be a valid value for the `organism_name` parameter.

Notice that, one can also uses other sets of compounds -- sets of compounds that are not provided within pre-built organisms -- by (i) setting `--organism_name` to `none` and (ii) using `--complementary_sink` to point the path to a 2 columns TSV file (name, inchi). See TSV files within the `data/sinks` directory for examples.

Best wishes,

**Comment by Teintes-BI** [comment]
It works! Thank you!

**Comment by tduigou** [comment]
Great to read! I close the issue.
