### ISSUE TITLE
Changing data path

### ISSUE THREAD

**Issue by muchlia** [brsynth/RetroPathRL#18]
Hello,
I have almost made it through the setup but I am stuck with these steps:
You need to specify in the config.py file where you want to store the data (data_path).
Unless specified, it will be stored in the package folder/data
Organisms will be stored in [data_path]/organisms (data_path should not end with a /) while rules in json format with ECFPS (optional) will be in [data_path]/rules

The first command ran as expected:
$ python calculate_rule_sets_similarity.py --rule_address_with_H ../retrorules_rr02_rp3_hs/retrorules_rr02_flat_all.tsv --rule_address_without_H ../retrorules_rr02_rp3_nohs/retrorules_rr02_flat_all.tsv 
By default, logs are saved in /Users/armk/RetroPathRL/RetroPathRL/data/rules/logs_rules_set_up.log. Please use --terminal to redirect to sys.stderr

The next one failed:
$ python calculate_organisms.py
Traceback (most recent call last):
  File "/Users/armk/RetroPathRL/RetroPathRL/calculate_organisms.py", line 14, in <module>
    from config import DATA_PATH
ImportError: cannot import name 'DATA_PATH' from 'config' (/Users/armk/RetroPathRL/RetroPathRL/config.py)

I am not sure how to change this data path. On MacOS using Terminal.

**Comment by tduigou** [comment]
Hello @muchlia,

Thanks for pointing this issue. This should now be fixed (commit aef1129). This now should work after pulling the last version of the code.

**Comment by tduigou** [comment]
@muchlia I reply to your question (https://github.com/brsynth/RetroPathRL/commit/aef112948602e4238a87bea1b1bb902af5f9e33c#commitcomment-143345800) here:

If you do want to change the value of DATA_PATH only change it at the following line:
https://github.com/brsynth/RetroPathRL/blob/ca0b01d1b8ec187ac9a891ef03999e5aefeec0b6/config.py#L17

However, it is not required to change the value of DATA_PATH, the default value is very fine. If the default value is kept, files will be written in `/Users/armk/RetroPathRL/RetroPathRL/Data` (it's a guess from your logs).

**Comment by muchlia** [comment]
Thank you I will give the new commit a try!
